# The overall format is standard TOML format, v0.5.0.
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[27,)" #mandatory
issueTrackerURL="https://github.com/Sinhika/SimpleOres2/issues"
logoFile="simple_ores.png"

[[mods]]
modId="simpleores"
version="${version}"
displayName="Simple Ores"
updateJSONURL="https://raw.githubusercontent.com/Sinhika/SimpleOres2/1.14/update.json"
displayURL="http://minecraft.curseforge.com/projects/simpleores"
credits="Thanks to AleXndrTheGr8st for creating the original mod and to Sinhika for porting and maintaining it."
authors="AleXndrTheGr8st, Sinhika"
description='''
A simple ore mod, featuring 5 balanced ores: Copper, Tin, Mythril, Adamantium and Onyx. 
All except Onyx can be found in the overworld, while Onyx can be found only in the Nether.
Each ore has its own unique properties, armor and tool sets, and more.
'''

[[dependencies.simpleores]] #optional
    modId="forge"
    mandatory=true
    versionRange="[27.0.49,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.simpleores]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"